apiVersion: apps/v1
kind: Deployment
metadata:
  name: pie-backend
  namespace: pie-development
spec:
  selector:
    matchLabels:
      run: pie-backend
  template:
    metadata:
      labels:
        run: pie-backend
    spec:
      containers:
      - name: pie-backend
        image: asia-south1-docker.pkg.dev/jiox-328108/pie-docker-development/pie-backend:latest
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: development
          - name: APIPORT
            value: "8000"
          - name: MONGO_URI
            value: mongodb+srv://bitelite:7coB2a95uR2ylV6A@cluster0.rvvg7.mongodb.net/bitelitedb
          - name: SECRET_MESSAGE
            value: Signing
          - name: JWT_SECRET
            value: 87kjbkdct72mn
          - name: JWT_TOKEN_EXPIRY
            value: 600m
          - name: WEB3_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDg0MzMwZjBFYUY1YmYyNTQ2NWRiMTlFMTVERThiRWIyOUFmOWYwNmIiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTc3ODAxNjE1MjAsIm5hbWUiOiJUU1YifQ.fI7E8MJcgS2v_JlhJ7OoGZyKMT96UV71Ncg0FKmxzUE
          - name: WALLABY_RPC_PROVIDER
            value: https://wallaby.node.glif.io/rpc/v0
          - name: ADMIN_PRIVATE_KEY
            value: 0x78129f6181d1f3493bf3fb4d1cdd4c751c2fa0acd67c130f729c4a782ec3f798
          - name: DEDUP_CONTRACT_ADDRESS
            value: 0xBBBd12E08D2Aa650192F2f04e5EE62a5E2Fc07aE