apiVersion: v1
kind: Service
metadata:
  name: pie-backend
  namespace: pie-development
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: pie-backend
  type: LoadBalancer
